name = "zipper-example"
defaultTargets = ["Zippers"]

[[require]]
name = "subverso"
git = "https://github.com/leanprover/subverso"
rev = "no-modules/ce893b9042128037e2d3c0158b9567fab9fae268"

[[lean_lib]]
name = "Zippers"
